"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarCheck2, ClipboardCheck, Download, FileBarChart, RefreshCw, Target, TrendingUp, Users } from "lucide-react";
import { toast } from "sonner";
import { download, post } from "@/lib/api";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
const reports=[{type:"daily",title:"Daily team report",description:"Daily output, hours, status and manager feedback.",icon:FileBarChart},{type:"weekly",title:"Weekly team report",description:"Weekly targets, attendance, reports and overall score.",icon:TrendingUp},{type:"monthly",title:"Monthly performance",description:"Monthly weighted employee performance summary.",icon:TrendingUp},{type:"employees",title:"Employee directory",description:"Employment, access, role and department details.",icon:Users},{type:"tasks",title:"Task report",description:"Assigned output, priority, status and deadlines.",icon:ClipboardCheck},{type:"targets",title:"Target report",description:"Target quantity, completion and achievement.",icon:Target},{type:"attendance",title:"Attendance report",description:"Check-in, check-out, hours and daily status.",icon:CalendarCheck2},{type:"performance",title:"Performance report",description:"Full weighted metric and rating breakdown.",icon:TrendingUp}];
export default function ReportCenter(){const [busy,setBusy]=useState("");async function exportFile(type:string,format:string){const key=type+format;setBusy(key);try{await download(`/reports/export?type=${type}&format=${format}`);toast.success(`${type} report downloaded.`)}catch(e){toast.error(e instanceof Error?e.message:"Export failed.")}finally{setBusy("")}}async function regenerate(){setBusy("generate");try{const r=await post("/performance/weekly/generate");toast.success(r.message)}catch(e){toast.error(e instanceof Error?e.message:"Generation failed.")}finally{setBusy("")}}return <div className="space-y-6"><Button asChild variant="ghost" size="sm"><Link href="/reports"><ArrowLeft className="h-4 w-4"/> Daily reports</Link></Button><PageHeader eyebrow="Exports & summaries" title="Admin report center" description="Generate operational and performance reports from current MongoDB records." actions={<Button variant="outline" onClick={regenerate} disabled={busy==="generate"}><RefreshCw className={`h-4 w-4 ${busy==="generate"?"animate-spin":""}`}/> Refresh weekly snapshots</Button>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reports.map(report=>{const Icon=report.icon;return <Card key={report.type}><CardHeader><div className="mb-2 grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-primary"><Icon className="h-5 w-5"/></div><CardTitle>{report.title}</CardTitle><CardDescription>{report.description}</CardDescription></CardHeader><CardContent><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>exportFile(report.type,"csv")} disabled={!!busy}><Download className="h-3.5 w-3.5"/> CSV</Button><Button variant="outline" size="sm" onClick={()=>exportFile(report.type,"xlsx")} disabled={!!busy}>Excel</Button><Button variant="outline" size="sm" onClick={()=>exportFile(report.type,"pdf")} disabled={!!busy}>PDF</Button></div></CardContent></Card>})}</div></div>}
