import { Router } from "express";
import auth from "./auth.routes.js";
import employees from "./employee.routes.js";
import tasks from "./task.routes.js";
import targets from "./target.routes.js";
import reports from "./report.routes.js";
import attendance from "./attendance.routes.js";
import performance from "./performance.routes.js";
import notifications from "./notification.routes.js";
import references from "./reference.routes.js";
import operations from "./operations.routes.js";
import { requireAuth } from "../middlewares/auth.js";
import { authorize } from "../middlewares/auth.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import * as dashboard from "../controllers/dashboard.controller.js";
const router = Router();
router.use("/auth", auth); router.use("/employees", employees); router.use("/tasks", tasks); router.use("/targets", targets); router.use("/reports", reports); router.use("/attendance", attendance); router.use("/performance", performance); router.use("/notifications", notifications); router.use("/references", references); router.use("/operations", operations);
router.get("/dashboard", requireAuth, asyncHandler(dashboard.dashboard));
router.get("/analytics", requireAuth, authorize("admin", "manager"), asyncHandler(dashboard.getAnalytics));
export default router;
